# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NetworkWidget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainGroupBox = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.mainGroupBox.setFont(font)
        self.mainGroupBox.setStyleSheet("")
        self.mainGroupBox.setObjectName("mainGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.propertyLayout = QtWidgets.QGridLayout()
        self.propertyLayout.setObjectName("propertyLayout")
        self.typeCombo = QtWidgets.QComboBox(self.mainGroupBox)
        self.typeCombo.setObjectName("typeCombo")
        self.typeCombo.addItem("")
        self.typeCombo.addItem("")
        self.typeCombo.addItem("")
        self.typeCombo.addItem("")
        self.typeCombo.addItem("")
        self.typeCombo.addItem("")
        self.propertyLayout.addWidget(self.typeCombo, 1, 1, 1, 1)
        self.nameEdit = QtWidgets.QLineEdit(self.mainGroupBox)
        self.nameEdit.setObjectName("nameEdit")
        self.propertyLayout.addWidget(self.nameEdit, 0, 1, 1, 1)
        self.endNodeColumnLabel = QtWidgets.QLabel(self.mainGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.endNodeColumnLabel.setFont(font)
        self.endNodeColumnLabel.setObjectName("endNodeColumnLabel")
        self.propertyLayout.addWidget(self.endNodeColumnLabel, 2, 0, 1, 1)
        self.componentCombo = QtWidgets.QComboBox(self.mainGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.componentCombo.setFont(font)
        self.componentCombo.setWhatsThis("")
        self.componentCombo.setObjectName("componentCombo")
        self.propertyLayout.addWidget(self.componentCombo, 2, 1, 1, 1)
        self.nameLabel = QtWidgets.QLabel(self.mainGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.nameLabel.setFont(font)
        self.nameLabel.setObjectName("nameLabel")
        self.propertyLayout.addWidget(self.nameLabel, 0, 0, 1, 1)
        self.typeLabel = QtWidgets.QLabel(self.mainGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.typeLabel.setFont(font)
        self.typeLabel.setObjectName("typeLabel")
        self.propertyLayout.addWidget(self.typeLabel, 1, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.propertyLayout)
        self.verticalLayout.addWidget(self.mainGroupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 42, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem1)
        self.validateButton = QtWidgets.QPushButton(Form)
        self.validateButton.setStatusTip("")
        self.validateButton.setObjectName("validateButton")
        self.buttonLayout.addWidget(self.validateButton)
        self.saveButton = QtWidgets.QPushButton(Form)
        self.saveButton.setStatusTip("")
        self.saveButton.setObjectName("saveButton")
        self.buttonLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.mainGroupBox.setTitle(_translate("Form", "Network"))
        self.typeCombo.setItemText(0, _translate("Form", "Node Only"))
        self.typeCombo.setItemText(1, _translate("Form", "Segment Only"))
        self.typeCombo.setItemText(2, _translate("Form", "Pressure Network"))
        self.typeCombo.setItemText(3, _translate("Form", "Hierarchical Network"))
        self.typeCombo.setItemText(4, _translate("Form", "Conduit Network"))
        self.typeCombo.setItemText(5, _translate("Form", "Data Network"))
        self.endNodeColumnLabel.setText(_translate("Form", "Network Component"))
        self.nameLabel.setText(_translate("Form", "Name"))
        self.typeLabel.setText(_translate("Form", "Type"))
        self.validateButton.setText(_translate("Form", "Validate"))
        self.saveButton.setText(_translate("Form", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

