# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'NodeNetworkWidget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainWidget(object):
    def setupUi(self, mainWidget):
        mainWidget.setObjectName("mainWidget")
        mainWidget.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(mainWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainGroupBox = QtWidgets.QGroupBox(mainWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.mainGroupBox.setFont(font)
        self.mainGroupBox.setStyleSheet("")
        self.mainGroupBox.setObjectName("mainGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.propertyLayout = QtWidgets.QGridLayout()
        self.propertyLayout.setObjectName("propertyLayout")
        self.tableTitleLabel = QtWidgets.QLabel(self.mainGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.tableTitleLabel.setFont(font)
        self.tableTitleLabel.setObjectName("tableTitleLabel")
        self.propertyLayout.addWidget(self.tableTitleLabel, 0, 0, 1, 1)
        self.tableTitleCombo = QtWidgets.QComboBox(self.mainGroupBox)
        self.tableTitleCombo.setWhatsThis("")
        self.tableTitleCombo.setObjectName("tableTitleCombo")
        self.propertyLayout.addWidget(self.tableTitleCombo, 0, 1, 1, 1)
        self.nodeIdColumnLabel = QtWidgets.QLabel(self.mainGroupBox)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.nodeIdColumnLabel.setFont(font)
        self.nodeIdColumnLabel.setObjectName("nodeIdColumnLabel")
        self.propertyLayout.addWidget(self.nodeIdColumnLabel, 1, 0, 1, 1)
        self.nodeIdColumnCombo = QtWidgets.QComboBox(self.mainGroupBox)
        self.nodeIdColumnCombo.setWhatsThis("")
        self.nodeIdColumnCombo.setObjectName("nodeIdColumnCombo")
        self.propertyLayout.addWidget(self.nodeIdColumnCombo, 1, 1, 1, 1)
        self.tableFilterLabel = QtWidgets.QLabel(self.mainGroupBox)
        self.tableFilterLabel.setObjectName("tableFilterLabel")
        self.propertyLayout.addWidget(self.tableFilterLabel, 2, 0, 1, 1)
        self.tableFilterEdit = QtWidgets.QLineEdit(self.mainGroupBox)
        self.tableFilterEdit.setWhatsThis("")
        self.tableFilterEdit.setObjectName("tableFilterEdit")
        self.propertyLayout.addWidget(self.tableFilterEdit, 2, 1, 1, 1)
        self.stopPredicateLabel = QtWidgets.QLabel(self.mainGroupBox)
        self.stopPredicateLabel.setObjectName("stopPredicateLabel")
        self.propertyLayout.addWidget(self.stopPredicateLabel, 3, 0, 1, 1)
        self.stopPredicateEdit = QtWidgets.QLineEdit(self.mainGroupBox)
        self.stopPredicateEdit.setWhatsThis("")
        self.stopPredicateEdit.setObjectName("stopPredicateEdit")
        self.propertyLayout.addWidget(self.stopPredicateEdit, 3, 1, 1, 1)
        self.snapToSegmentLabel = QtWidgets.QLabel(self.mainGroupBox)
        self.snapToSegmentLabel.setObjectName("snapToSegmentLabel")
        self.propertyLayout.addWidget(self.snapToSegmentLabel, 4, 0, 1, 1)
        self.snapToSegmentLayout = QtWidgets.QHBoxLayout()
        self.snapToSegmentLayout.setObjectName("snapToSegmentLayout")
        self.snapToSegmentYes = QtWidgets.QRadioButton(self.mainGroupBox)
        self.snapToSegmentYes.setObjectName("snapToSegmentYes")
        self.snapToSegmentLayout.addWidget(self.snapToSegmentYes)
        self.snapToSegmentNo = QtWidgets.QRadioButton(self.mainGroupBox)
        self.snapToSegmentNo.setObjectName("snapToSegmentNo")
        self.snapToSegmentLayout.addWidget(self.snapToSegmentNo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.snapToSegmentLayout.addItem(spacerItem)
        self.propertyLayout.addLayout(self.snapToSegmentLayout, 4, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.propertyLayout)
        self.verticalLayout.addWidget(self.mainGroupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 113, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem2)
        self.validateButton = QtWidgets.QPushButton(mainWidget)
        self.validateButton.setStatusTip("")
        self.validateButton.setObjectName("validateButton")
        self.buttonLayout.addWidget(self.validateButton)
        self.saveButton = QtWidgets.QPushButton(mainWidget)
        self.saveButton.setStatusTip("")
        self.saveButton.setObjectName("saveButton")
        self.buttonLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(mainWidget)
        QtCore.QMetaObject.connectSlotsByName(mainWidget)

    def retranslateUi(self, mainWidget):
        _translate = QtCore.QCoreApplication.translate
        mainWidget.setWindowTitle(_translate("mainWidget", "Form"))
        self.mainGroupBox.setTitle(_translate("mainWidget", "Node Component"))
        self.tableTitleLabel.setText(_translate("mainWidget", "Table title"))
        self.nodeIdColumnLabel.setText(_translate("mainWidget", "Node ID Column"))
        self.tableFilterLabel.setText(_translate("mainWidget", "Table Filter"))
        self.stopPredicateLabel.setText(_translate("mainWidget", "Stop Predicate"))
        self.snapToSegmentLabel.setText(_translate("mainWidget", "Snap to Segment"))
        self.snapToSegmentYes.setText(_translate("mainWidget", "Yes"))
        self.snapToSegmentNo.setText(_translate("mainWidget", "No"))
        self.validateButton.setText(_translate("mainWidget", "Validate"))
        self.saveButton.setText(_translate("mainWidget", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWidget = QtWidgets.QWidget()
    ui = Ui_mainWidget()
    ui.setupUi(mainWidget)
    mainWidget.show()
    sys.exit(app.exec_())

