# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SegmentNetworkWidget.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainGroupBox = QtWidgets.QGroupBox(Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.mainGroupBox.setFont(font)
        self.mainGroupBox.setStyleSheet("")
        self.mainGroupBox.setObjectName("mainGroupBox")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.mainGroupBox)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.propertyLayout = QtWidgets.QGridLayout()
        self.propertyLayout.setObjectName("propertyLayout")
        self.tableTitleLabel = QtWidgets.QLabel(self.mainGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableTitleLabel.setFont(font)
        self.tableTitleLabel.setObjectName("tableTitleLabel")
        self.propertyLayout.addWidget(self.tableTitleLabel, 0, 0, 1, 1)
        self.tableTitleCombo = QtWidgets.QComboBox(self.mainGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableTitleCombo.setFont(font)
        self.tableTitleCombo.setWhatsThis("")
        self.tableTitleCombo.setObjectName("tableTitleCombo")
        self.propertyLayout.addWidget(self.tableTitleCombo, 0, 1, 1, 1)
        self.startNodeColumnLabel = QtWidgets.QLabel(self.mainGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.startNodeColumnLabel.setFont(font)
        self.startNodeColumnLabel.setObjectName("startNodeColumnLabel")
        self.propertyLayout.addWidget(self.startNodeColumnLabel, 1, 0, 1, 1)
        self.startNodeColumnCombo = QtWidgets.QComboBox(self.mainGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.startNodeColumnCombo.setFont(font)
        self.startNodeColumnCombo.setWhatsThis("")
        self.startNodeColumnCombo.setObjectName("startNodeColumnCombo")
        self.propertyLayout.addWidget(self.startNodeColumnCombo, 1, 1, 1, 1)
        self.endNodeColumnLabel = QtWidgets.QLabel(self.mainGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.endNodeColumnLabel.setFont(font)
        self.endNodeColumnLabel.setObjectName("endNodeColumnLabel")
        self.propertyLayout.addWidget(self.endNodeColumnLabel, 2, 0, 1, 1)
        self.endNodeColumnCombo = QtWidgets.QComboBox(self.mainGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.endNodeColumnCombo.setFont(font)
        self.endNodeColumnCombo.setWhatsThis("")
        self.endNodeColumnCombo.setObjectName("endNodeColumnCombo")
        self.propertyLayout.addWidget(self.endNodeColumnCombo, 2, 1, 1, 1)
        self.tableFilterLabel = QtWidgets.QLabel(self.mainGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableFilterLabel.setFont(font)
        self.tableFilterLabel.setObjectName("tableFilterLabel")
        self.propertyLayout.addWidget(self.tableFilterLabel, 3, 0, 1, 1)
        self.tableFilterEdit = QtWidgets.QLineEdit(self.mainGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tableFilterEdit.setFont(font)
        self.tableFilterEdit.setWhatsThis("")
        self.tableFilterEdit.setObjectName("tableFilterEdit")
        self.propertyLayout.addWidget(self.tableFilterEdit, 3, 1, 1, 1)
        self.stopPredicateLabel = QtWidgets.QLabel(self.mainGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.stopPredicateLabel.setFont(font)
        self.stopPredicateLabel.setObjectName("stopPredicateLabel")
        self.propertyLayout.addWidget(self.stopPredicateLabel, 4, 0, 1, 1)
        self.stopPredicateEdit = QtWidgets.QLineEdit(self.mainGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.stopPredicateEdit.setFont(font)
        self.stopPredicateEdit.setWhatsThis("")
        self.stopPredicateEdit.setObjectName("stopPredicateEdit")
        self.propertyLayout.addWidget(self.stopPredicateEdit, 4, 1, 1, 1)
        self.snapToNodesLabel = QtWidgets.QLabel(self.mainGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.snapToNodesLabel.setFont(font)
        self.snapToNodesLabel.setObjectName("snapToNodesLabel")
        self.propertyLayout.addWidget(self.snapToNodesLabel, 5, 0, 1, 1)
        self.snapToNodesLayout = QtWidgets.QHBoxLayout()
        self.snapToNodesLayout.setObjectName("snapToNodesLayout")
        self.snapToNodesYes = QtWidgets.QRadioButton(self.mainGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.snapToNodesYes.setFont(font)
        self.snapToNodesYes.setObjectName("snapToNodesYes")
        self.snapToNodesLayout.addWidget(self.snapToNodesYes)
        self.snapToNodesNo = QtWidgets.QRadioButton(self.mainGroupBox)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.snapToNodesNo.setFont(font)
        self.snapToNodesNo.setObjectName("snapToNodesNo")
        self.snapToNodesLayout.addWidget(self.snapToNodesNo)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.snapToNodesLayout.addItem(spacerItem)
        self.propertyLayout.addLayout(self.snapToNodesLayout, 5, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.propertyLayout)
        self.verticalLayout.addWidget(self.mainGroupBox)
        spacerItem1 = QtWidgets.QSpacerItem(20, 89, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem2)
        self.validateButton = QtWidgets.QPushButton(Form)
        self.validateButton.setStatusTip("")
        self.validateButton.setObjectName("validateButton")
        self.buttonLayout.addWidget(self.validateButton)
        self.saveButton = QtWidgets.QPushButton(Form)
        self.saveButton.setStatusTip("")
        self.saveButton.setObjectName("saveButton")
        self.buttonLayout.addWidget(self.saveButton)
        self.verticalLayout.addLayout(self.buttonLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.mainGroupBox.setTitle(_translate("Form", "Segment Component"))
        self.tableTitleLabel.setText(_translate("Form", "Table title"))
        self.startNodeColumnLabel.setText(_translate("Form", "Start Node Column"))
        self.endNodeColumnLabel.setText(_translate("Form", "End Node Column"))
        self.tableFilterLabel.setText(_translate("Form", "Table Filter"))
        self.stopPredicateLabel.setText(_translate("Form", "Stop Predicate"))
        self.snapToNodesLabel.setText(_translate("Form", "Snap to Nodes"))
        self.snapToNodesYes.setText(_translate("Form", "Yes"))
        self.snapToNodesNo.setText(_translate("Form", "No"))
        self.validateButton.setText(_translate("Form", "Validate"))
        self.saveButton.setText(_translate("Form", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

